SET NOCOUNT ON;
SET XACT_ABORT ON;

/*
  Controlled opening balances for Note 3.2A. The values are keyed to the
  retained prior-year source document, so they are only available when that
  exact document is the active Prior Year Financial Statements upload.
*/
IF OBJECT_ID('dbo.tblNORM_SourceAssetMovementFigure','U') IS NULL
BEGIN
    CREATE TABLE dbo.tblNORM_SourceAssetMovementFigure
    (
        SourceAssetMovementFigureId BIGINT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_tblNORM_SourceAssetMovementFigure PRIMARY KEY,
        SourceFileHash CHAR(64) NOT NULL,
        RowCode VARCHAR(40) NOT NULL,
        AssetClassCode VARCHAR(60) NOT NULL,
        Amount DECIMAL(19,3) NOT NULL,
        SourceReference NVARCHAR(300) NULL,
        IsDeactivated BIT NOT NULL
            CONSTRAINT DF_tblNORM_SourceAssetMovementFigure_IsDeactivated DEFAULT (0),
        CreatedUtc DATETIME2(3) NOT NULL
            CONSTRAINT DF_tblNORM_SourceAssetMovementFigure_CreatedUtc DEFAULT SYSUTCDATETIME(),
        CONSTRAINT UQ_tblNORM_SourceAssetMovementFigure
            UNIQUE(SourceFileHash,RowCode,AssetClassCode)
    );
END;

DECLARE @Hash CHAR(64)='1D02B0EE80D807735035CEED18EB7871D0D50193845DB6E7317335F3CA9CD62B';
DECLARE @Source NVARCHAR(300)=N'Defence Annual Report 2023-24, Note 3.2A, closing balances at 30 June 2024';
DECLARE @Figures TABLE(RowCode VARCHAR(40),AssetClassCode VARCHAR(60),Amount DECIMAL(19,3));

INSERT @Figures VALUES
('CLOSING_GROSS','LAND',7033480),
('CLOSING_GROSS','BUILDINGS',21367067),
('CLOSING_GROSS','SPECIALIST_MILITARY_EQUIPMENT',89422981),
('CLOSING_GROSS','INFRASTRUCTURE',9848632),
('CLOSING_GROSS','PLANT_EQUIPMENT',2125524),
('CLOSING_GROSS','HERITAGE_CULTURAL',416580),
('CLOSING_GROSS','COMPUTER_SOFTWARE_PURCHASED',1760147),
('CLOSING_GROSS','COMPUTER_SOFTWARE_INTERNALLY_GENERATED',1262420),
('CLOSING_GROSS','OTHER_INTANGIBLES_PURCHASED',2341939),
('CLOSING_GROSS','OTHER_INTANGIBLES_INTERNALLY_GENERATED',200508),

('CLOSING_ACCUMULATED','LAND',0),
('CLOSING_ACCUMULATED','BUILDINGS',-1701526),
('CLOSING_ACCUMULATED','SPECIALIST_MILITARY_EQUIPMENT',-794919),
('CLOSING_ACCUMULATED','INFRASTRUCTURE',-401867),
('CLOSING_ACCUMULATED','PLANT_EQUIPMENT',-484206),
('CLOSING_ACCUMULATED','HERITAGE_CULTURAL',-14909),
('CLOSING_ACCUMULATED','COMPUTER_SOFTWARE_PURCHASED',-784835),
('CLOSING_ACCUMULATED','COMPUTER_SOFTWARE_INTERNALLY_GENERATED',-760204),
('CLOSING_ACCUMULATED','OTHER_INTANGIBLES_PURCHASED',-230155),
('CLOSING_ACCUMULATED','OTHER_INTANGIBLES_INTERNALLY_GENERATED',-167242),

('CLOSING_CARRYING','LAND',7033480),
('CLOSING_CARRYING','BUILDINGS',19665541),
('CLOSING_CARRYING','SPECIALIST_MILITARY_EQUIPMENT',88628062),
('CLOSING_CARRYING','INFRASTRUCTURE',9446765),
('CLOSING_CARRYING','PLANT_EQUIPMENT',1641318),
('CLOSING_CARRYING','HERITAGE_CULTURAL',401671),
('CLOSING_CARRYING','COMPUTER_SOFTWARE_PURCHASED',975312),
('CLOSING_CARRYING','COMPUTER_SOFTWARE_INTERNALLY_GENERATED',502216),
('CLOSING_CARRYING','OTHER_INTANGIBLES_PURCHASED',2111784),
('CLOSING_CARRYING','OTHER_INTANGIBLES_INTERNALLY_GENERATED',33266),

('RIGHT_OF_USE_CARRYING','LAND',53923),
('RIGHT_OF_USE_CARRYING','BUILDINGS',1970000),
('RIGHT_OF_USE_CARRYING','SPECIALIST_MILITARY_EQUIPMENT',206943),
('RIGHT_OF_USE_CARRYING','INFRASTRUCTURE',79459),
('RIGHT_OF_USE_CARRYING','PLANT_EQUIPMENT',301451),
('RIGHT_OF_USE_CARRYING','HERITAGE_CULTURAL',0),
('RIGHT_OF_USE_CARRYING','COMPUTER_SOFTWARE_PURCHASED',0),
('RIGHT_OF_USE_CARRYING','COMPUTER_SOFTWARE_INTERNALLY_GENERATED',0),
('RIGHT_OF_USE_CARRYING','OTHER_INTANGIBLES_PURCHASED',0),
('RIGHT_OF_USE_CARRYING','OTHER_INTANGIBLES_INTERNALLY_GENERATED',0);

UPDATE target
SET target.Amount=source.Amount,target.SourceReference=@Source,target.IsDeactivated=0
FROM dbo.tblNORM_SourceAssetMovementFigure target
INNER JOIN @Figures source
    ON source.RowCode=target.RowCode AND source.AssetClassCode=target.AssetClassCode
WHERE target.SourceFileHash=@Hash;

INSERT dbo.tblNORM_SourceAssetMovementFigure
    (SourceFileHash,RowCode,AssetClassCode,Amount,SourceReference)
SELECT @Hash,source.RowCode,source.AssetClassCode,source.Amount,@Source
FROM @Figures source
WHERE NOT EXISTS
(
    SELECT 1 FROM dbo.tblNORM_SourceAssetMovementFigure target
    WHERE target.SourceFileHash=@Hash AND target.RowCode=source.RowCode
      AND target.AssetClassCode=source.AssetClassCode
);

IF (SELECT SUM(Amount) FROM @Figures WHERE RowCode='CLOSING_GROSS')<>135779278
    THROW 51060, 'Note 3.2A prior-year gross book value control failed.', 1;
IF (SELECT SUM(Amount) FROM @Figures WHERE RowCode='CLOSING_ACCUMULATED')<>-5339863
    THROW 51061, 'Note 3.2A prior-year accumulated depreciation control failed.', 1;
IF (SELECT SUM(Amount) FROM @Figures WHERE RowCode='CLOSING_CARRYING')<>130439415
    THROW 51062, 'Note 3.2A prior-year closing carrying amount control failed.', 1;

PRINT 'NORM controlled Note 3.2A opening balances installed.';
